### ISSUE TITLE
Error: stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by chadswen** [cilium/k8s-1abel#6]
I tried `./k8s-1abel services` in a cluster with 924 k8s Services, looks like I hit a default buffer threshold?

# Stack Trace
```
./k8s-1abel services
{ Error: stdout maxBuffer exceeded
    at Socket.onChildStdout (child_process.js:328:14)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20) cmd: 'kubectl get services --all-namespaces -o=json' }
```

**Comment by michi-covalent** [comment]
Hi @chadswen yeah the buffer size is hardcoded right now: https://github.com/cilium/k8s-1abel/blob/be32255fdcc727305446a92e0527da5bf3884580/src/main.ts#L76

we can either increase the hardcoded value, or maybe make it configurable?

**Comment by chadswen** [comment]
@michi-covalent I'm fine with either solution, thanks!

**Comment by michi-covalent** [comment]
@tgraf i need your help pushing a new release.

**Comment by michi-covalent** [comment]
hi @chadswen i'm planning to create a docker image for the new release this weekend so that k8s-1abel can be deployed as a pod. i'll update this issue when it's ready.

**Comment by michi-covalent** [comment]
in the new version `0.0.2` the default buffer size is 50mb, and there is `-b` option to override the default. 

please follow https://github.com/cilium/k8s-1abel#installation--usage to deploy k8s-1abel as a pod.
